### ISSUE TITLE
[FR] Allow to listen to multiple exchanges

### ISSUE THREAD

**Issue by antonincms** [Templum/rabbitmq-connector#33]
**Is your feature request related to a problem? Please describe.**
In my workflow, we'd like to react to existing events, pushed by different microservices (let say A and B) which commit their actions in different Exchange (AEx and BEx). 

**Describe the solution you'd like**
I would nice think to have a list of echanges, instead of only one :
```yaml
RMQ_EXCHANGES : 
  - AEx
  - BEx
```
 Maybe more precisely, each exchange could have their topics to listen ?
```yaml
RMQ_EXCHANGES:
- name: AEx
  topics:
  - Foo
  - Bar
- name: BEx
  topics:
  - Dead
  - Beef
```
Which can also be writen 
```yaml
RMQ_EXCHANGES:
- name: AEx
  topics: [Foo, Bar]
- name: BEx
  topics: [Dead, Beef]
```
**Describe alternatives you've considered**
Having some kind of worker to copy-paste events from AEx and BEx to OpenFaasEx, but this is neither convenient  nor a good practice.
