### ISSUE TITLE
example usage of topology

### ISSUE THREAD

**Issue by gshenai1** [Templum/rabbitmq-connector#94]
Can somebody provide an example using the topology? updating the artifact with an example would be helpful. I get the error "During Config validation provided topology is either non existing or does not end with .yaml occurred"

**Comment by Templum** [comment]
Please check out the [Example Yaml](https://github.com/Templum/rabbitmq-connector/blob/develop/artifacts/example_topology.yaml). I do believe that is more than straightforward.

If you still struggle, feel free to share it here.

**Comment by Templum** [comment]
Based on your reported error, it seems that there is no file under the specified path. As this is what is [checked](https://github.com/Templum/rabbitmq-connector/blob/4cb1576bee81953c1b64de6a699e35e990233fcf/pkg/config/config.go#L125-L127). Therefore you should make sure the file is present, for k8s you can have a look at this [article](https://carlos.mendible.com/2019/02/10/kubernetes-mount-file-pod-with-configmap/).

**Comment by gshenai1** [comment]
thank you very much. I had observed the error in the k8s environment. Thank you also for sharing the k8s article, it was very helpful.  To get rid of the error, I followed the poor man's way - which was download the git repo and build the docker image with the topology.yaml and then pushed it to my k8s environment - but the link you shared is the elegant solution. Everything is working for me now, thanks once again

**Comment by yididiyag** [comment]
Hello here, I am encountering the same issue:
```
During Config validation provided topology is either non existing or does not end with .yaml occurred.
maxprocs: Updating GOMAXPROCS=1: using minimum allowed GOMAXPROCS
OpenFaaS RabbitMQ Connector [Version: dev Commit: cf2276c]
```
here is my connector-dep.yaml file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-connector
  namespace: openfaas
spec:
  selector:
    matchLabels:
      app: rabbitmq-connector
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-connector
    spec:
      containers:
      - name: connector
        image: templum/rabbitmq-connector:develop
        imagePullPolicy: Always
        env:
        - name: basic_auth
          value: "false"
        - name: OPEN_FAAS_GW_URL
          value: "http://gateway.openfaas.svc.cluster.local:8080"
        - name: RMQ_TOPICS
          value: "yido"
        - name: RMQ_HOST
          value: "rabbit-rabbitmq.openfaas.svc.cluster.local"
        - name: RMQ_PORT
          value: "15672"
        - name: RMQ_USER
          value: "user"
        - name: RMQ_PASS
          value: "password"
        - name: REQ_TIMEOUT
          value: "3000s"
        - name: TOPIC_MAP_REFRESH_TIME
          value: "30s"
        resources: # Adjust them to suite your needs
          requests:
            memory: 256Mi
          limits:
            memory: 512Mi
            cpu: "0.5"
        volumeMounts:
          - name: config-volume
            mountPath: /config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: rabbitmq-connector-configmap
```

here is my config.yaml file:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-connector-configmap
data:
  config.yaml: |
    OPEN_FAAS_GW_URL: "http://gateway.openfaas.svc.cluster.local:8080"
    RMQ_TOPICS: "yido"
    RMQ_HOST: "rabbit-rabbitmq.openfaas.svc.cluster.local"
    RMQ_PORT: "15672"
    RMQ_USER: "user"
    RMQ_PASS: "password"  
    REQ_TIMEOUT: "3000s"
    TOPIC_MAP_REFRESH_TIME: "30s"
```

hi @gshenai1 can you share your config & connector-deployment.config files so that I can see where I am at fault.

cc: @Templum
